apiVersion: v1
kind: ConfigMap
metadata:
  name: microshop-config
  namespace: microshop
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "ordersdb"
  DB_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: microshop-secret
  namespace: microshop
type: Opaque
stringData:
  DB_PASS: "postgres"
  GF_ADMIN_PASSWORD: "admin"
